name: Node.js CI

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
      - run: yarn test
      - run: yarn lint
      - run: yarn package:rebuild --compress Brotli

      - name: Codecov
        if: matrix.node-version == '18.x'
        uses: codecov/codecov-action@v2.1.0

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && matrix.node-version == '18.x'
        with:
          draft: true
          fail_on_unmatched_files: true
          files: bin/*
